version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - guitartuto-network
    depends_on:
      - backend
      - frontend

  backend:
    image: pdelebarre/guitar-tutorial-app-backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      TUTORIALS_PATH: /app/tutorials
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - /Volumes/LaCie/dev/guitar-tutorial-app/tutorials:/app/tutorials
    networks:
      - guitartuto-network
    restart: unless-stopped

  frontend:
    image: pdelebarre/guitar-tutorial-app-frontend
    container_name: frontend
    environment:
      TUTO_API_URL: http://nginx/api  # Set API URL to go through Nginx
    ports:
      - "3000:80"  # Uncomment if you want direct access to frontend on port 3000
    networks:
      - guitartuto-network

networks:
  guitartuto-network:
    driver: bridge
