services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Adapt path for the container
      TUTORIALS_PATH: /app/tutorials  # Use an internal path inside the container

      # Default to dev profile (using H2)
      SPRING_PROFILES_ACTIVE: dev
      
    volumes:
      - /Volumes/LaCie/dev/guitar-tutorial-app/tutorials:/app/tutorials
    networks:
      - guitartuto-network
    # Do not include depends_on here, so backend is independent in dev

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    image: pdelebarre/frontend:${BUILD_ENV:-dev}
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://backend:8080/api
    depends_on:
      - backend
    networks:
      - guitartuto-network

networks:
  guitartuto-network:
    driver: bridge
