services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "3050:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend

  backend:
    image: pdelebarre/guitar-tutorial-app-backend
    platform: linux/amd64  # Add this line
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      TUTORIALS_PATH: /app/tutorials
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - /Volumes/LaCie/dev/guitar-tutorial-app/tutorials:/app/tutorials
    restart: unless-stopped

  frontend:
    stdin_open: true
    image: pdelebarre/guitar-tutorial-app-frontend
    container_name: frontend

