version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: guitardb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - springboot-network

  backend:
    environment:
      # Set the profile to prod and connect to Postgres
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/guitardb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      
    volumes:
      - /Volumes/LaCie/dev/guitar-tutorial-app/tutorials:/app/tutorials  # Map local to container path

    depends_on:
      - postgres  # Postgres should only be used in prod mode

networks:
  springboot-network:
    driver: bridge
