services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"  # Expose NGINX on port 80
    networks:
      - guitartuto-network
    depends_on:
      - backend
  backend:
    container_name: backend
    image: pdelebarre/guitar-tutorial-app-backend
    # :${BUILD_ENV:-dev}
    ports:
      - "8080:8080"
    environment:
      TUTORIALS_PATH: /app/tutorials  # Use an internal path inside the container
      # Default to dev profile (using H2)
      SPRING_PROFILES_ACTIVE: dev
      
    volumes:
      - /Volumes/LaCie/dev/guitar-tutorial-app/tutorials:/app/tutorials
    networks:
      - guitartuto-network
    restart: unless-stopped
    # Do not include depends_on here, so backend is independent in dev

  frontend:
    container_name: frontend
    image: pdelebarre/guitar-tutorial-app-frontend
    environment:
        TUTO_API_URL: http://nginx
        TUTO_API_PORT: 8080
    ports:
      - "3000:80"
    depends_on:
      - backend
      - nginx
    networks:
      - guitartuto-network

networks:
  guitartuto-network:
    driver: bridge
    name: guitartuto-network
