# Default application settings
spring:
  profiles:
    active: dev  # Default profile for local development

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true 
     # Log SQL queries
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true  # Enable H2 console for development
      path: /h2-console

  servlet:
    multipart:
      max-file-size: 100MB  # Max file size for uploads
      max-request-size: 100MB

tutorials:
  path: /Volumes/LaCie/dev/guitar-tutorial-app/tutorials

logging:
  level:
    root: INFO  # Set root log level to INFO
    org.hibernate.SQL: DEBUG  # Enable SQL logging in dev environment

# Profile-specific configurations for development (dev)
---
spring:
  config:
    activate:
      on-profile: dev  # New syntax to activate dev profile

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      platform: h2  # Specify H2 as platform for SQL initialization

tutorials:
  path: /Volumes/LaCie/dev/guitar-tutorial-app/tutorials
# Profile-specific configurations for production (prod)
---
spring:
  config:
    activate:
      on-profile: prod  # New syntax to activate prod profile

  datasource:
    url: jdbc:postgresql://db:5432/guitardb  # Postgres database in Docker Compose
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}  # Environment variable
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}  # Environment variable

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false  # Don't log SQL in production

tutorials:
  path: /Volumes/LaCie/dev/guitar-tutorial-app/tutorials
